"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { fetchOrganization, updateOrganization } from "@/lib/api";
import { Alert, EmptyState, ErrorState, Skeleton } from "@/components/ui/feedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StatusBadge } from "@/components/ui/badge";
import type { OrganizationRecord, OrganizationStatus } from "@/features/organizations/types";

export default function OrganizationDetailPage() {
  const { organizationId } = useParams<{ organizationId: string }>();
  const [organization, setOrganization] = useState<OrganizationRecord | null>(null);
  const [form, setForm] = useState({ name: "", legal_name: "", industry: "", country: "", timezone: "", billing_email: "", status: "lead" as OrganizationStatus });
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const record = await fetchOrganization(organizationId); setOrganization(record); setForm({ name: record.name, legal_name: record.legal_name ?? "", industry: record.industry ?? "", country: record.country ?? "", timezone: record.timezone ?? "", billing_email: record.billing_email ?? "", status: record.status }); } catch (cause) { setError(cause instanceof Error ? cause.message : "The company could not be loaded."); } finally { setLoading(false); } }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!organization || !form.name.trim()) { setError("Company name is required."); return; } setSaving(true); setError(null); setMessage(null); try { const updated = await updateOrganization(organization.id, { ...form, name: form.name.trim(), legal_name: form.legal_name.trim() || undefined, industry: form.industry.trim() || undefined, country: form.country.trim() || undefined, timezone: form.timezone.trim() || undefined, billing_email: form.billing_email.trim() || undefined }); setOrganization(updated); setMessage("Company details saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "The company could not be updated."); } finally { setSaving(false); } }
  if (loading) return <div className="space-y-6"><Skeleton className="h-28" /><Skeleton className="h-96" /></div>;
  if (!organization) return <ErrorState title={error && causeIsNotFound(error) ? "Company not found" : "Company unavailable"} description={error ?? "The company record is unavailable."} onRetry={() => void load()} />;
  return <div className="space-y-6"><PageHeader eyebrow="Customers / Company" title={organization.name} description={`${organization.industry ?? "Industry not set"} · ${organization.country ?? "Country not set"}`} actions={<><Link className="ui-button ui-button-secondary" href={`/app/organizations/${organization.id}/tenants`}>View ERP sites</Link><Link className="ui-button ui-button-ghost" href="/app/organizations">Back to companies</Link></>} /><div className="grid gap-6 lg:grid-cols-[1fr_.42fr]"><Card><CardHeader><CardTitle>Edit company</CardTitle></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-2" onSubmit={save}><Field label="Company name"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Legal name"><Input value={form.legal_name} onChange={(event) => setForm({ ...form, legal_name: event.target.value })} /></Field><Field label="Industry"><Input value={form.industry} onChange={(event) => setForm({ ...form, industry: event.target.value })} /></Field><Field label="Country"><Input value={form.country} onChange={(event) => setForm({ ...form, country: event.target.value })} /></Field><Field label="Timezone"><Input value={form.timezone} onChange={(event) => setForm({ ...form, timezone: event.target.value })} /></Field><Field label="Billing email"><Input type="email" value={form.billing_email} onChange={(event) => setForm({ ...form, billing_email: event.target.value })} /></Field><Field label="Status"><Select value={form.status} onValueChange={(value) => setForm({ ...form, status: value as OrganizationStatus })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["lead", "trial", "active", "suspended", "cancelled", "archived"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></Field><div className="flex items-center gap-3 md:col-span-2"><Button type="submit" loading={saving}>Save changes</Button>{message ? <span className="text-sm" style={{ color: "var(--color-success)" }} role="status">{message}</span> : null}</div>{error ? <div className="md:col-span-2"><Alert tone="danger">{error}</Alert></div> : null}</form></CardContent></Card><Card><CardHeader><CardTitle>Account status</CardTitle></CardHeader><CardContent className="space-y-4"><StatusBadge status={organization.status} /><dl className="space-y-3 text-sm"><div><dt style={{ color: "var(--color-muted)" }}>Billing email</dt><dd>{organization.billing_email ?? "Not set"}</dd></div><div><dt style={{ color: "var(--color-muted)" }}>Timezone</dt><dd>{organization.timezone ?? "Not set"}</dd></div><div><dt style={{ color: "var(--color-muted)" }}>Created</dt><dd>{new Date(organization.created_at).toLocaleDateString()}</dd></div></dl><Link className="ui-button ui-button-secondary w-full" href={`/app/organizations/${organization.id}/tenants`}>Manage ERP sites</Link></CardContent></Card></div></div>;
}

function causeIsNotFound(message: string) { return /not found/i.test(message); }
