"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Search } from "lucide-react";
import { StatusBadge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState, ErrorState, Skeleton } from "@/components/ui/feedback";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { fetchTenants } from "@/lib/api";
import type { TenantRecord } from "@/features/tenants/types";

export default function TenantsPage() {
  const [tenants, setTenants] = useState<TenantRecord[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setTenants(await fetchTenants()); } catch (cause) { setError(cause instanceof Error ? cause.message : "ERP sites are unavailable."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => tenants.filter((tenant) => (!query || `${tenant.tenant_slug} ${tenant.primary_domain ?? ""} ${tenant.organization_id}`.toLowerCase().includes(query.toLowerCase())) && (status === "all" || tenant.status === status || tenant.provisioning_status === status)), [tenants, query, status]);
  return <div className="space-y-6"><PageHeader eyebrow="Customers" title="ERP sites" description="Review environment, provisioning, domain, and runtime status for each site." actions={<Link className="ui-button ui-button-primary" href="/app/tenants/new">Create ERP site</Link>} /><Card><CardContent><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2" style={{ color: "var(--color-muted)" }} aria-hidden="true" /><Input className="pl-9" aria-label="Search ERP sites" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by slug, domain, or company" /></div><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="Filter sites by status" className="w-48"><SelectValue /></SelectTrigger><SelectContent>{["all", "planned", "provisioning", "ready", "suspended", "failed", "archived", "pending", "queued", "running"].map((item) => <SelectItem key={item} value={item}>{item === "all" ? "All statuses" : item}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>{loading ? <Skeleton className="h-72" /> : error ? <ErrorState description={error} onRetry={() => void load()} /> : !filtered.length ? <EmptyState title={tenants.length ? "No ERP sites match" : "No ERP sites yet"} description={tenants.length ? "Try another search or filter." : "Create a site record to track readiness."} action={!tenants.length ? { label: "Create ERP site", href: "/app/tenants/new" } : undefined} /> : <Table><TableHeader><TableRow><TableHead>Site</TableHead><TableHead>Environment</TableHead><TableHead>Domain</TableHead><TableHead>Provisioning</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map((tenant) => <TableRow key={tenant.id}><TableCell><Link className="font-bold hover:underline" href={`/app/tenants/${tenant.id}`}>{tenant.tenant_slug}</Link><p className="mt-1 text-xs" style={{ color: "var(--color-muted)" }}>Company {tenant.organization_id.slice(0, 8)}</p></TableCell><TableCell className="capitalize">{tenant.environment}</TableCell><TableCell>{tenant.primary_domain ?? tenant.custom_domain ?? "Not configured"}</TableCell><TableCell><StatusBadge status={tenant.provisioning_status} /></TableCell><TableCell><StatusBadge status={tenant.status} /></TableCell><TableCell><Link className="ui-button ui-button-secondary" href={`/app/tenants/${tenant.id}`}>Open</Link></TableCell></TableRow>)}</TableBody></Table>}<div className="flex justify-between text-xs" style={{ color: "var(--color-muted)" }}><span>{filtered.length} of {tenants.length} sites</span><Button variant="ghost" onClick={() => void load()}>Refresh</Button></div></div>;
}
