"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Alert, Skeleton } from "@/components/ui/feedback";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { createTenant, fetchOrganizations } from "@/lib/api";
import type { OrganizationRecord } from "@/features/organizations/types";

export default function NewTenantPage() {
  const router = useRouter(); const [organizations, setOrganizations] = useState<OrganizationRecord[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ organization_id: "", tenant_slug: "", environment: "demo", primary_domain: "", custom_domain: "", erpnext_site_name: "", erpnext_base_url: "" });
  useEffect(() => { fetchOrganizations().then((items) => { setOrganizations(items); setForm((current) => ({ ...current, organization_id: current.organization_id || items[0]?.id || "" })); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Companies are unavailable.")).finally(() => setLoading(false)); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.organization_id || !form.tenant_slug.trim()) { setError("Company and site slug are required."); return; } setBusy(true); setError(null); try { const created = await createTenant({ ...form, tenant_slug: form.tenant_slug.trim(), primary_domain: form.primary_domain.trim() || undefined, custom_domain: form.custom_domain.trim() || undefined, erpnext_site_name: form.erpnext_site_name.trim() || undefined, erpnext_base_url: form.erpnext_base_url.trim() || undefined }); router.push(`/app/tenants/${created.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "The ERP site could not be created."); } finally { setBusy(false); } }
  if (loading) return <div className="space-y-6"><Skeleton className="h-24" /><Skeleton className="h-96" /></div>;
  return <div className="space-y-6"><PageHeader eyebrow="Customers / ERP sites" title="Create ERP site" description="Add a site record and its environment/domain plan. Provisioning remains a separate controlled action." /><Card className="max-w-3xl"><CardHeader><CardTitle>Site details</CardTitle></CardHeader><CardContent>{!organizations.length ? <Alert tone="warning">Create a company before adding an ERP site.</Alert> : <form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><Field label="Company"><Select value={form.organization_id} onValueChange={(value) => setForm({ ...form, organization_id: value })}><SelectTrigger><SelectValue placeholder="Select a company" /></SelectTrigger><SelectContent>{organizations.map((organization) => <SelectItem key={organization.id} value={organization.id}>{organization.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Site slug"><Input autoFocus value={form.tenant_slug} onChange={(event) => setForm({ ...form, tenant_slug: event.target.value })} placeholder="north-ridge-demo" /></Field><Field label="Environment"><Select value={form.environment} onValueChange={(value) => setForm({ ...form, environment: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="demo">Demo</SelectItem><SelectItem value="staging">Staging</SelectItem><SelectItem value="production">Production</SelectItem></SelectContent></Select></Field><Field label="Primary domain"><Input value={form.primary_domain} onChange={(event) => setForm({ ...form, primary_domain: event.target.value })} placeholder="north-ridge.example.test" /></Field><Field label="Custom domain"><Input value={form.custom_domain} onChange={(event) => setForm({ ...form, custom_domain: event.target.value })} placeholder="ops.example.test" /></Field><Field label="ERP site name"><Input value={form.erpnext_site_name} onChange={(event) => setForm({ ...form, erpnext_site_name: event.target.value })} placeholder="Optional site reference" /></Field><Field label="ERP base URL"><Input value={form.erpnext_base_url} onChange={(event) => setForm({ ...form, erpnext_base_url: event.target.value })} placeholder="https://erp.example.test" /></Field><div className="flex gap-3 md:col-span-2"><Button type="submit" loading={busy}>Create ERP site</Button><Button type="button" variant="ghost" onClick={() => router.back()}>Cancel</Button></div>{error ? <div className="md:col-span-2"><Alert tone="danger">{error}</Alert></div> : null}</form>}</CardContent></Card></div>;
}
